/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Match_H
#define Match_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "match_types.h"

namespace match {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class MatchIf {
 public:
  virtual ~MatchIf() {}
  virtual int32_t add(const User& user) = 0;
  virtual int32_t remove(const User& user) = 0;
};

class MatchIfFactory {
 public:
  typedef MatchIf Handler;

  virtual ~MatchIfFactory() {}

  virtual MatchIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MatchIf* /* handler */) = 0;
  };

class MatchIfSingletonFactory : virtual public MatchIfFactory {
 public:
  MatchIfSingletonFactory(const ::std::shared_ptr<MatchIf>& iface) : iface_(iface) {}
  virtual ~MatchIfSingletonFactory() {}

  virtual MatchIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(MatchIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<MatchIf> iface_;
};

class MatchNull : virtual public MatchIf {
 public:
  virtual ~MatchNull() {}
  int32_t add(const User& /* user */) override {
    int32_t _return = 0;
    return _return;
  }
  int32_t remove(const User& /* user */) override {
    int32_t _return = 0;
    return _return;
  }
};

typedef struct _Match_add_args__isset {
  _Match_add_args__isset() : user(false) {}
  bool user :1;
} _Match_add_args__isset;

class Match_add_args {
 public:

  Match_add_args(const Match_add_args&);
  Match_add_args& operator=(const Match_add_args&);
  Match_add_args() noexcept {
  }

  virtual ~Match_add_args() noexcept;
  User user;

  _Match_add_args__isset __isset;

  void __set_user(const User& val);

  bool operator == (const Match_add_args & rhs) const
  {
    if (!(user == rhs.user))
      return false;
    return true;
  }
  bool operator != (const Match_add_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Match_add_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Match_add_pargs {
 public:


  virtual ~Match_add_pargs() noexcept;
  const User* user;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Match_add_result__isset {
  _Match_add_result__isset() : success(false) {}
  bool success :1;
} _Match_add_result__isset;

class Match_add_result {
 public:

  Match_add_result(const Match_add_result&) noexcept;
  Match_add_result& operator=(const Match_add_result&) noexcept;
  Match_add_result() noexcept
                   : success(0) {
  }

  virtual ~Match_add_result() noexcept;
  int32_t success;

  _Match_add_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const Match_add_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Match_add_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Match_add_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Match_add_presult__isset {
  _Match_add_presult__isset() : success(false) {}
  bool success :1;
} _Match_add_presult__isset;

class Match_add_presult {
 public:


  virtual ~Match_add_presult() noexcept;
  int32_t* success;

  _Match_add_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _Match_remove_args__isset {
  _Match_remove_args__isset() : user(false) {}
  bool user :1;
} _Match_remove_args__isset;

class Match_remove_args {
 public:

  Match_remove_args(const Match_remove_args&);
  Match_remove_args& operator=(const Match_remove_args&);
  Match_remove_args() noexcept {
  }

  virtual ~Match_remove_args() noexcept;
  User user;

  _Match_remove_args__isset __isset;

  void __set_user(const User& val);

  bool operator == (const Match_remove_args & rhs) const
  {
    if (!(user == rhs.user))
      return false;
    return true;
  }
  bool operator != (const Match_remove_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Match_remove_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Match_remove_pargs {
 public:


  virtual ~Match_remove_pargs() noexcept;
  const User* user;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Match_remove_result__isset {
  _Match_remove_result__isset() : success(false) {}
  bool success :1;
} _Match_remove_result__isset;

class Match_remove_result {
 public:

  Match_remove_result(const Match_remove_result&) noexcept;
  Match_remove_result& operator=(const Match_remove_result&) noexcept;
  Match_remove_result() noexcept
                      : success(0) {
  }

  virtual ~Match_remove_result() noexcept;
  int32_t success;

  _Match_remove_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const Match_remove_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Match_remove_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Match_remove_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Match_remove_presult__isset {
  _Match_remove_presult__isset() : success(false) {}
  bool success :1;
} _Match_remove_presult__isset;

class Match_remove_presult {
 public:


  virtual ~Match_remove_presult() noexcept;
  int32_t* success;

  _Match_remove_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class MatchClient : virtual public MatchIf {
 public:
  MatchClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MatchClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t add(const User& user) override;
  void send_add(const User& user);
  int32_t recv_add();
  int32_t remove(const User& user) override;
  void send_remove(const User& user);
  int32_t recv_remove();
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MatchProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<MatchIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (MatchProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_add(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_remove(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MatchProcessor(::std::shared_ptr<MatchIf> iface) :
    iface_(iface) {
    processMap_["add"] = &MatchProcessor::process_add;
    processMap_["remove"] = &MatchProcessor::process_remove;
  }

  virtual ~MatchProcessor() {}
};

class MatchProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MatchProcessorFactory(const ::std::shared_ptr< MatchIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< MatchIfFactory > handlerFactory_;
};

class MatchMultiface : virtual public MatchIf {
 public:
  MatchMultiface(std::vector<std::shared_ptr<MatchIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MatchMultiface() {}
 protected:
  std::vector<std::shared_ptr<MatchIf> > ifaces_;
  MatchMultiface() {}
  void add(::std::shared_ptr<MatchIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int32_t add(const User& user) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->add(user);
    }
    return ifaces_[i]->add(user);
  }

  int32_t remove(const User& user) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->remove(user);
    }
    return ifaces_[i]->remove(user);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class MatchConcurrentClient : virtual public MatchIf {
 public:
  MatchConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  MatchConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t add(const User& user) override;
  int32_t send_add(const User& user);
  int32_t recv_add(const int32_t seqid);
  int32_t remove(const User& user) override;
  int32_t send_remove(const User& user);
  int32_t recv_remove(const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
